import { VideoItem, GraphicItem, SoftwareTool } from './types';

export const USER_INFO = {
  name: 'MAHMUDUL HASAN MASUM',
  displayName: 'Mahmudul Hasan Masum',
  role: 'Video Editor • Graphic Designer • Meta Marketer',
  subTitle: 'High-Retention Video Editing, Creative Visual Design & ROAS-Driven Meta Ads',
  email: 'mahmud2026k@gmail.com',
  whatsappRaw: '01832313750',
  whatsappFormatted: '+880 1832-313750',
  whatsappLink: 'https://wa.me/8801832313750?text=Hi%20Masum,%20I%20saw%20your%20portfolio%20(Video%20Editing,%20Graphic%20Design,%20Meta%20Marketing)%20and%20would%20like%20to%20collaborate!',
  facebookProfile: 'https://www.facebook.com/profile.php?id=61577322251551',
  xProfile: 'https://x.com/home?lang=en',
  twitterProfile: 'https://x.com/home?lang=en',
  address: 'House-364, Satarkul Road, Uttar Badda, Dhaka-12',
  addressShort: 'Uttar Badda, Dhaka-12',
  honestBio:
    "I am a versatile creative professional specializing in high-retention Video Editing, Graphic Design, and Meta Ads Marketing. Over the past several months, I have dedicated myself to mastering visual storytelling—crafting dynamic video cuts in Premiere Pro, After Effects, and CapCut, designing high-converting thumbnails and posters in Photoshop and Illustrator, and scaling digital brands through targeted Meta ad creatives. I bring fresh creativity, rapid execution, and a modern aesthetic to every project. Let's create something memorable together.",
  skills: [
    { title: 'Dynamic Pacing & Retention', desc: 'Precision cutting on the beat, shaping tension and energy to maximize viewer watch time.' },
    { title: 'Motion Graphics & VFX', desc: 'Kinetic typography, seamless transitions, 3D text tracking, and visual polish in After Effects.' },
    { title: 'Thumbnail & Poster Design', desc: 'High-CTR visual concepts, creative composition, and vivid color grading in Photoshop & Illustrator.' },
    { title: 'Short-Form Viral Growth', desc: 'TikTok, YouTube Shorts, and Facebook Reels optimized for algorithm retention via CapCut & Premiere.' },
    { title: 'Meta Ads Creative Strategy', desc: 'Scroll-stopping video ads and banners tailored for Facebook & Instagram high-ROAS marketing campaigns.' },
    { title: 'Rapid Daily Turnaround', desc: 'High-energy dedication, prompt communication, and continuous refinement based on client goals.' },
  ],
};

export const SOFTWARE_TOOLS: SoftwareTool[] = [
  {
    id: 'premiere-pro',
    name: 'Adobe Premiere Pro',
    shortName: 'Pr',
    category: 'Video Editing',
    roleTag: 'Video Editing',
    description: 'Precision timeline cuts, audio sync, sound design, color grading & long-form/short-form assembly.',
    badgeBg: 'bg-[#9999FF]/15',
    badgeColor: 'text-[#B8B8FF]',
    accentBorder: 'border-[#9999FF]/40',
    level: 'Advanced Timeline Mastery',
  },
  {
    id: 'after-effects',
    name: 'Adobe After Effects',
    shortName: 'Ae',
    category: 'Motion & VFX',
    roleTag: 'VFX & Motion Graphics',
    description: 'Kinetic typography, visual effects, 3D camera tracking, smooth speed ramps & dynamic motion overlays.',
    badgeBg: 'bg-[#D291FF]/15',
    badgeColor: 'text-[#E0B0FF]',
    accentBorder: 'border-[#D291FF]/40',
    level: 'Motion & Visual Polish',
  },
  {
    id: 'photoshop',
    name: 'Adobe Photoshop',
    shortName: 'Ps',
    category: 'Graphic Design',
    roleTag: 'Graphic Design',
    description: 'High-CTR YouTube thumbnails, promotional poster concepts, photo retouching, and digital brand visuals.',
    badgeBg: 'bg-[#31A8FF]/15',
    badgeColor: 'text-[#64B5F6]',
    accentBorder: 'border-[#31A8FF]/40',
    level: 'Key Visuals & Poster Art',
  },
  {
    id: 'illustrator',
    name: 'Adobe Illustrator',
    shortName: 'Ai',
    category: 'Graphic Design',
    roleTag: 'Graphic Design',
    description: 'Vector graphics, branding marks, clean badge typography, scalable icons, and social media layout design.',
    badgeBg: 'bg-[#FF9A00]/15',
    badgeColor: 'text-[#FFA726]',
    accentBorder: 'border-[#FF9A00]/40',
    level: 'Vector Art & Branding',
  },
  {
    id: 'capcut',
    name: 'CapCut Pro',
    shortName: 'Cc',
    category: 'Video Editing',
    roleTag: 'Short-Form Video',
    description: 'Viral TikToks & Reels, trending audio beat matching, auto captions, speed ramps, and rapid-fire cuts.',
    badgeBg: 'bg-[#00F2FE]/15',
    badgeColor: 'text-[#4DD0E1]',
    accentBorder: 'border-[#00F2FE]/40',
    level: 'Viral Short-Form Speed',
  },
  {
    id: 'kinemaster',
    name: 'KineMaster',
    shortName: 'Km',
    category: 'Video Editing',
    roleTag: 'Mobile Video',
    description: 'Multi-track mobile editing, chroma key, instant format delivery, and responsive social cuts on mobile.',
    badgeBg: 'bg-[#FF3366]/15',
    badgeColor: 'text-[#FF6B8B]',
    accentBorder: 'border-[#FF3366]/40',
    level: 'Mobile Video Production',
  },
  {
    id: 'meta-marketing',
    name: 'Meta Ads & Marketing',
    shortName: 'Meta',
    category: 'Digital Marketing',
    roleTag: 'Meta Marketing',
    description: 'Facebook & Instagram ad campaigns, high-converting video hooks, audience targeting, and ROAS scaling.',
    badgeBg: 'bg-[#0081FB]/15',
    badgeColor: 'text-[#42A5F5]',
    accentBorder: 'border-[#0081FB]/40',
    level: 'Ad Strategy & ROAS Scaling',
  },
];

export const FEATURED_VIDEO: VideoItem = {
  id: 'featured-trailer',
  title: 'Visual Rhythm • Best Work Showcase',
  tag: 'Featured Highlight',
  sourceUrl: 'https://www.youtube.com/shorts/7-4GKg2K0cE',
  embedUrl: 'https://www.youtube-nocookie.com/embed/7-4GKg2K0cE',
  platform: 'youtube',
  aspectRatio: '16/9',
};

export const PORTFOLIO_VIDEOS: VideoItem[] = [
  {
    id: 'video-1',
    title: 'Kinetic Edit 01',
    tag: 'Short-Form Reel',
    sourceUrl: 'https://www.youtube.com/shorts/1Q_cR71UGuk',
    embedUrl: 'https://www.youtube-nocookie.com/embed/1Q_cR71UGuk',
    platform: 'youtube',
    aspectRatio: '9/16',
  },
  {
    id: 'video-2',
    title: 'Visual Flow 02',
    tag: 'Dynamic Cut',
    sourceUrl: 'https://www.youtube.com/shorts/OJMtDsnlC6c',
    embedUrl: 'https://www.youtube-nocookie.com/embed/OJMtDsnlC6c',
    platform: 'youtube',
    aspectRatio: '9/16',
  },
  {
    id: 'video-3',
    title: 'Rhythm & Impact 03',
    tag: 'Short-Form Reel',
    sourceUrl: 'https://www.youtube.com/shorts/x48dOQQ3Xok',
    embedUrl: 'https://www.youtube-nocookie.com/embed/x48dOQQ3Xok',
    platform: 'youtube',
    aspectRatio: '9/16',
  },
  {
    id: 'video-4',
    title: 'Logo Animation & Motion Graphics',
    tag: 'After Effects Motion',
    sourceUrl: 'https://youtu.be/4sOAjFusWDI',
    embedUrl: 'https://www.youtube-nocookie.com/embed/4sOAjFusWDI',
    platform: 'youtube',
    aspectRatio: '16/9',
  },
  {
    id: 'video-5',
    title: 'Motion Video Edit',
    tag: 'Motion & VFX',
    sourceUrl: 'https://youtu.be/0LxIu7gW8l0',
    embedUrl: 'https://www.youtube-nocookie.com/embed/0LxIu7gW8l0',
    platform: 'youtube',
    aspectRatio: '16/9',
  },
];

export const GRAPHIC_WORKS: GraphicItem[] = [
  {
    id: 'graphic-1',
    src: 'graphic1.jpg',
    imageUrl: 'graphic1.jpg',
    title: 'Graphic Poster Concept 01',
    category: 'Promotional Banner',
    alt: 'Graphic design poster 1 created by Mahmudul Hasan Masum',
  },
  {
    id: 'graphic-2',
    src: 'graphic2.jpg',
    imageUrl: 'graphic2.jpg',
    title: 'Graphic Poster Concept 02',
    category: 'Thumbnail & Key Art',
    alt: 'Graphic design poster 2 created by Mahmudul Hasan Masum',
  },
  {
    id: 'graphic-3',
    src: 'graphic3.jpg',
    imageUrl: 'graphic3.jpg',
    title: 'Graphic Poster Concept 03',
    category: 'Social Media Graphic',
    alt: 'Graphic design poster 3 created by Mahmudul Hasan Masum',
  },
  {
    id: 'graphic-4',
    src: 'graphic4.jpg',
    imageUrl: 'graphic4.jpg',
    title: 'Graphic Poster Concept 04',
    category: 'Commercial Art',
    alt: 'Graphic design poster 4 created by Mahmudul Hasan Masum',
  },
  {
    id: 'graphic-5',
    src: 'graphic5.jpg',
    imageUrl: 'graphic5.jpg',
    title: 'Graphic Poster Concept 05',
    category: 'Event & Promo Poster',
    alt: 'Graphic design poster 5 created by Mahmudul Hasan Masum',
  },
  {
    id: 'graphic-6',
    src: 'graphic6.jpg',
    imageUrl: 'graphic6.jpg',
    title: 'Graphic Poster Concept 06',
    category: 'Motion Background Art',
    alt: 'Graphic design poster 6 created by Mahmudul Hasan Masum',
  },
];
